losers/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name='inicio'),
    path('contacto/', views.contacto, name="contacto"),
    path('sobremi/', views.sobremi, name="sobremi"),
    path('publicaciones/', include('publicaciones.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publicaciones/urls.py
from django.urls import path, re_path
from . import views

app_name ="publicaciones"

urlpatterns = [
    path('nueva/', views.nueva_publicacion,name="nueva"),
    #re_path(r'^(?P<pk>[0-9]+)/$', views.ver_publicacion,name="ver_publicacion"),
    path('<int:id_publicacion>/', views.ver_publicacion ,name="ver_publicacion"),
    #path('editar/<int:publicacion_id>',views.editar_publicacion,name="editar"),
]

publicaciones/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

class Publicacion(models.Model):
    nombre = models.CharField(max_length=300)
    contenido = RichTextUploadingField(blank=True,null=True)
    imagen_fondo = models.FileField()
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.nombre
        

losers/forms.py
from django import forms

class FormContacto(forms.Form):

    nombre = forms.CharField(required=True,max_length=200,widget=forms.TextInput(attrs={'placeholder':'Nombre','autocomplete':'off'}))
    correo = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'Correo','autocomplete':'off'} ))
    mensaje = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Mensaje','autocomplete':'off'}),max_length=None)

publicaciones/forms.py
from django.forms import ModelForm
from django import forms
from .models import Publicacion

class PublicacionForm(ModelForm):
    
    class Meta:
        model = Publicacion
        fields = ['nombre','contenido','imagen_fondo']

losers/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from publicaciones.models import Publicacion
from django.core.mail import send_mail
from .forms import FormContacto

def inicio(request):
    
    publicaciones = Publicacion.objects.all()

    contexto = {
        'publicaciones': publicaciones
    }

    return render(request, 'inicio.html',contexto)

def contacto(request):
    
    formulario = FormContacto(request.POST or None)

    if formulario.is_valid():

        correo = formulario.cleaned_data.get('correo')
        mensaje = formulario.cleaned_data.get('mensaje')
        nombre = formulario.cleaned_data.get('nombre')

        correo_mensaje = '%s: %s enviado por %s' %(nombre, mensaje, correo)

        send_mail(
            nombre,
            correo_mensaje,
            correo,
            ['pedroesparzaaa@gmail.com'],
            fail_silently=False,
        )
    
    formulario = FormContacto()

    contexto = {'formulario': formulario}

    return render(request, 'contacto.html',contexto)

def sobremi(request):

    return render(request, 'sobremi.html',{})
        

publicaciones/views.py
from django.shortcuts import render, redirect, render_to_response
from django.http import HttpResponse

from .forms import PublicacionForm
from .models import Publicacion
# Create your views here.

def nueva_publicacion(request):

    form = PublicacionForm(request.POST or None,request.FILES)

    if(form.is_valid()):
        publicacion = form.save()
        form = PublicacionForm()
        publicacion.save()

    return render(request, 'nueva_publicacion.html', {'form':form})

'''
def editar_publicacion(request):

    return HttpResponse("Editando Publicacion")
'''

def ver_publicacion(request,id_publicacion):    

    publicacion = Publicacion.objects.get(pk=id_publicacion)

    return render(request,'ver_publicacion.html',{'publicacion':publicacion})
    #return render_to_response('ver_publicacion.html',{'publicacion':publicacion})

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans|Patua+One" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/init.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/botones.css' %}">
    <link rel="stylesheet" href="{% static 'css/formulario.css' %}">
    {% block links_templates %}
    {% endblock links_templates %}

    <title>{% block titulo %}{% endblock titulo %}</title>
</head>
<body>
    <header class="navegacion">
        <!-- Logo-->
        <div class="contenedor_imagen_header">
            <a href="{% url 'inicio' %}"><img class="imagen_header" src="{% static 'img/logo.jpg' %}" alt=""></a>
        </div>
        <!-- nav -->
        <nav class="menu">
            <a href="{% url 'inicio' %}" class="enlaces_menu">Inicio</a>
            <a href="{% url 'contacto' %}" class="enlaces_menu">Contacto</a>
            <a href="#" class="enlaces_menu">Reseñas</a>
            <a href="{% url 'sobremi' %}" class="enlaces_menu">Conóceme</a>
        </nav>
    </header>
    {% block contenedor_entra %}{% endblock contenedor_entra %}
    <main class="principal">
        {% block contenido %}
          
        {% endblock contenido %}
    </main>
    <footer>
        <div class="sobre_mi">
            <h4 class="sobre_mi_encabezado">Este solo es un Footer mas</h4>
            <p class="motivaciones">"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."</p>
        </div>
        <div class="sigueme">
            <h5 class="sigueme_encabezado">Sígueme</h5>
            <a href="https://www.facebook.com/eydenv"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a>
            <a href="https://github.com/EydenVillanueva"><i class="fa fa-github fa-2x" aria-hidden="true"></i></a>
        </div>
    </footer>


    <script src="{% static 'js/jquery.js' %}"></script>
    {% block scripts_extra %}
    
    {% endblock scripts_extra %}
    
</body>
</html>

templates/contacto.html
{% extends "base.html" %}
{% load staticfiles %}


{% block links_templates %}
<link rel="stylesheet" href="{% static 'css/contacto.css' %}">
{% endblock links_templates %}

{% block titulo %}Contacto{% endblock titulo %}

{% block contenido %}
    <div class="contactame">
        <h1>Contáctame</h1>
    </div>
    <div class="formulario">
        <form action="{% url 'contacto' %}" class="formulario_contacto" method="post">
            {% csrf_token %}
            {{formulario.nombre}}
            {{formulario.correo}}
            {{formulario.mensaje}}
            <input type="submit" value="Enviar" class="boton">
        </form>
    </div>
{% endblock contenido %}


{% block scripts_extra %}
      
{% endblock scripts_extra %}

templates/inicio.html
{% extends "base.html" %}
{% load staticfiles %}

{% block links_templates %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">  
<link rel="stylesheet" href="{% static 'css/bienvenida.css' %}">  
{% endblock links_templates %}

{% block titulo %}Losers Club{% endblock titulo %}

{% block contenedor_entra %}
<section class="contenedor_bienvenida">
    <div class="bienvenida">
        <h2>Bienvenidos a mi Blog, Encontrarán Reseñas, Articulos y mis Opiniones</h2>
    </div>
</section>
{% endblock contenedor_entra %}


{% block contenido %}


<main class="principal">
    {% for publicacion in publicaciones %}
    {% url 'publicaciones:ver_publicacion' publicacion.id as the_url %}
    <article class="articulo">
        <a href="{{the_url}}">
            <div class="articulo_encabezado">
                <h4 class="articulo_titulo">{{publicacion.nombre}}</h4>
                <span class="articulo_fecha">{{publicacion.fecha}}</span>
            </div>
            <div class="articulo_cuerpo">
                <img src="{{publicacion.imagen_fondo.url}}" alt="{{publicacion.nombre}}">
            </div>
        </a>
    </article>
    {% endfor %}
  
</main>
{% endblock contenido %}

{% block scripts_extra %}
    <script src="{% static 'js/index.js' %}"></script>
{% endblock scripts_extra %}

templates/nueva_publicacion.html
{% extends "base.html" %}
{% load staticfiles %}


{% block links_templates %}


<link rel="stylesheet" href="{% static 'css/nueva_entrada.css' %}">

{% endblock links_templates %}

{% block titulo %}
Nueva Entrada  
{% endblock titulo %}


{% block contenido %}
    <form action="{% url 'publicaciones:nueva' %}" method="post" class="formulario grande" enctype="multipart/form-data" novalidate="">
        {% csrf_token %}
        {{form.media}}
        {{form}}
        <input type="submit" value="Guardar" class="boton">
    </form>
{% endblock contenido %}


{% block scripts_extra %}

{% endblock scripts_extra %}

templates/sobremi.html
{% extends "base.html" %}
{% load staticfiles %}


{% block links_templates %}
<link rel="stylesheet" href="{% static 'css/sobremi.css' %}">
{% endblock links_templates %}

{% block titulo %}Sobre Mi{% endblock titulo %}

{% block contenido %}
    <div class="contenedor_imagen">
        <img class="imagen" src="{% static 'img/yo.jpg' %}" alt="">
    </div>
    <div class="contenedor_conoceme">
        <h1 class="conoceme">Sobre Mí</h1>
        <div class="contenedor_intro">
            <p>
                Me llamo Eyden, estudio ingeniería y este es mi espacio personal.
            </p>
            <p>
                Soy gran aficionado al cine, a los libros, a la música y también a dar mi opinión acerca
                de los temas que conozco. Soy una persona introvertida que disfruta de su propia compañia.
                <span>"Quién no es buena compañia para si mismo, nunca lo será para los demás"</span>
            </p>
            <p>
                Me sentiré bien en responder todos sus comentarios y en debatir acerca de mis opinones sobre 
                libros y películas.
            </p>
        </div>
    </div>
{% endblock contenido %}

templates/ver_publicacion.html
{% extends "base.html" %}
{% load staticfiles %}

{% block links_templates %}
<link rel="stylesheet" href="{% static 'css/entrada.css' %}">
{% endblock links_templates %}


{% block titulo %}
    {{publicacion.nombre}}
{% endblock titulo %}

{% block contenido %}
    <div class="contenedor_titulo_imagen">
        <div class="contenedor_titulo">
            <img src="{{publicacion.imagen_fondo.url}}" alt="">
            <h1>{{publicacion.nombre}}</h1>
        </div>
    </div>   
    <div class="hidden" id="hidden">
        {{publicacion.contenido}}
    </div>
    <div class="contenido" id="contenido"></div>
{% endblock contenido %}



{% block scripts_extra %}

<script>
    var publicacion = document.getElementById("hidden").innerText;
    var $contenedor = $("#contenido");
    html = $.parseHTML(publicacion);
    $contenedor.append(html);
</script>
  
{% endblock scripts_extra %}